name: Feature request
description: Suggest a backwards-compatible improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Use case
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed behavior
    validations:
      required: true
